### ISSUE TITLE
Acess geth from another machine (same local network)

### ISSUE THREAD

**Issue by ArdalanM** [stereum-dev/ethereum2-docker-compose#208]
Hello,

I am running docker geth with default settings

```
geth:
    image: ethereum/client-go:${GETH_DOCKER_TAG}
    restart: always
    hostname: geth
    command: --http --http.port=8545 --http.addr=0.0.0.0 --http.vhosts="*" --allow-insecure-unlock --http.api="db,eth,net,web3,personal"
    stop_grace_period: 5m
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - ${BEACON_API_IP}:8545:8545
 ```

A simple curl post

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' http://localhost:8545
```

works on the host machine but doesn't from another local machine (replaced localhost with local ip) 

I installed geth without docker and I can successfully access it from another computer.

What am I missing ?
